services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: socialdata
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=socialdata
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
